### ISSUE TITLE
It's a fake

### ISSUE THREAD

**Issue by glowiak** [exalpha-dev/exalpha-dev.github.io#3]
https://www.reddit.com/r/Minecraft/comments/v09iit/the_alpha_101605_is_fake/

Also, this site was made just on day the 'Discovered' video was published.

I mean, it's a nice texturepack, but at least it'd be good to tell people that this isn't official

**Comment by counter185** [comment]
no shit

**Comment by glowiak** [comment]
Java 7 was not a thing in 2010, which this version is targeted at. This is a fake

**Comment by counter185** [comment]
please don't tell me you actually thought an ARG about a """hidden minecraft fork with shadow players""" was reuploads of real footage
