### ISSUE TITLE
Cool mod

### ISSUE THREAD

**Issue by MrMasrozYTLIVE** [exalpha-dev/exalpha-dev.github.io#4]
Mod is cool but what the point in keys if they can be removed by editing just 1 thing in decompiled version?

**Comment by exalpha-dev** [comment]
"This is not production code. In their original releases, the jars was further obfuscated, preventing any kind of bypass."
"Unfortunately, we are yet to locate these original obfuscated jars."
"I could have theoretically run the second obfuscation, but for the purposes of preservation I didn't."

- [6]

**Comment by MrMasrozYTLIVE** [comment]
Understandble but i still dont understand the point of keys if they not even synced with anything

**Comment by defyspace** [comment]
ok and

**Comment by MrMasrozYTLIVE** [comment]
> ok and

ok and

**Comment by EsperWonder** [comment]
> Understandble but i still dont understand the point of keys if they not even synced with anything

They don't really need to be synced to anything.

This isn't an account system, instead it serves to make sure people come from the videos on these versions.

It doesn't need to be vital, it just needs to be.
