### ISSUE TITLE
How much is preserved?

### ISSUE THREAD

**Issue by Nosh-Ware** [exalpha-dev/exalpha-dev.github.io#7]
I understand there is clearly alot of effort to track down and pull out alot of the code here, but I have to ask: Is any code being modified as it is (or will be) posted? Is this repo more focused on getting a function version working or is this a straight dump of the files?

**Comment by suspecting** [comment]
> each file was signed with their usernames, IPs and their matched approximate locations

Why, if I may ask?

**Comment by exalpha-dev** [comment]
> Why, if I may ask?

So that they could track down where it leaked from

**Comment by suspecting** [comment]
> > Why, if I may ask?
> 
> So that they could track down where it leaked from

What would happen if someone DID leak it? Are there any citations of someone leaking it, for that matter? Or would they just call the cops?

**Comment by MrMasrozYTLIVE** [comment]
I dont think cops will care about leaking mod that literally breaking Minecraft ToS

**Comment by mdo992** [comment]
> What would happen if someone DID leak it? Are there any citations of someone leaking it, for that matter? Or would they just call the cops?

If someone did leak it, the development team would be eligible to file a lawsuit against the user whom the leaked file belonged to, possibly. You wont know exactly *who* leaked it, but you can assure that the jar was shared and sourced from the tester.

I would recommend @exalpha-dev to add on to this.

**Comment by MrMasrozYTLIVE** [comment]
> eligible to file a lawsuit against the user whom the leaked file belonged to,
But dont this mod breaking laws?

**Comment by zai-tm** [comment]
How is this mod even close to breaking laws

**Comment by MrMasrozYTLIVE** [comment]
> How is this mod even close to breaking laws

Minecraft ToS, it doesnt allow you to publish ANYHOW edited Minecraft jar and Minecraft SRC

**Comment by MrMasrozYTLIVE** [comment]
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/mods-discussion/1393961-can-i-distribute-old-minecraft-jar-file-and-what

**Comment by Vladg24YT** [comment]
> Minecraft ToS, it doesn't allow you to publish ANYHOW edited Minecraft jar and Minecraft SRC

Actually, modern ToS does allow mods:

> We are also quite relaxed about other non-commercial things so feel free to create and share videos, screen shots, independently created mods (that don't use any of our Assets), fan art, machinima, etc.

But then there is a question - where is the line between an alteration and a modification?

**Comment by suspecting** [comment]
> I dont think cops will care about leaking mod that literally breaking Minecraft ToS

Canonically it's actual minecraft. Just was in alpha.

**Comment by mdo992** [comment]
> But dont this mod breaking laws?

Yes, however I doubt Mojang or the mod writers are going to do anything about it.

**Comment by Vincent392** [comment]
> > What would happen if someone DID leak it? Are there any citations of someone leaking it, for that matter? Or would they just call the cops?
> 
> If someone did leak it, the development team would be eligible to file a lawsuit against the user whom the leaked file belonged to, possibly. You wont know exactly *who* leaked it, but you can assure that the jar was shared and sourced from the tester.
> 
> I would recommend @exalpha-dev to add on to this.

Wouldn't say they would sue but they would send the playtester to the ash dimension.
