### ISSUE TITLE
Can't download it

### ISSUE THREAD

**Issue by paliszarok** [exalpha-dev/exalpha-dev.github.io#9]
I'm trying to download it but it redirects me to about:blank, I know that this is not accidental, is there any ways to get the game?

**Comment by exalpha-dev** [comment]
You can find download links in the descriptions of some of our videos.

**Comment by Vincent392** [comment]
> You can find download links in the descriptions of some of our videos.

And get modded jars that add skin support or Moding support ect.
And there are mirrors of the jars. If the mediafire links dont work. (Even at that you just change their file extention from .zip to .jar)

**Comment by Vincent392** [comment]
Also the download page doesn't exist. [6] and the others dont have it. Even if Memories of 0b99-1ac2 on the RGN Discord Server found R4's jar and The Launcher they still dont have the page. Also R4's jar has [0]'s personal info or something.
